# Generated by Django 5.0.4 on 2024-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
