# Generated by Django 5.0.4 on 2024-06-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='courses/'),
            preserve_default=False,
        ),
    ]
