# Generated by Django 5.0.4 on 2024-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_certification_chapter_option_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(default='', upload_to='course_pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='', upload_to='course_videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
